function createfigure2(zdata1)
%CREATEFIGURE2(ZDATA1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 10-Oct-2013 18:06:21

% Create figure
figure1 = figure('Colormap',...
    [0 0 0.560784339904785;0 0 0.623529434204102;0 0 0.686274528503418;0 0 0.749019622802734;0 0 0.811764717102051;0 0 0.874509811401367;0 0 0.937254905700684;0 0 1;0 0.062745101749897 1;0 0.125490203499794 1;0 0.18823529779911 1;0 0.250980406999588 1;0 0.313725501298904 1;0 0.376470595598221 1;0 0.439215689897537 1;0 0.498039215803146 1;0 0.560784339904785 1;0 0.623529434204102 1;0 0.686274528503418 1;0 0.749019622802734 1;0 0.811764717102051 1;0 0.874509811401367 1;0 0.937254905700684 1;0 1 1;0 1 0.874509811401367;0 1 0.749019622802734;0 1 0.623529434204102;0 1 0.501960813999176;0 1 0.376470595598221;0 1 0.250980406999588;0 1 0.125490203499794;0 1 0;0.125490203499794 1 0;0.250980406999588 1 0;0.376470595598221 1 0;0.501960813999176 1 0;0.623529434204102 1 0;0.749019622802734 1 0;0.874509811401367 1 0;1 1 0;1 0.937254905700684 0;1 0.874509811401367 0;1 0.811764717102051 0;1 0.749019622802734 0;1 0.686274528503418 0;1 0.623529434204102 0;1 0.560784339904785 0;1 0.501960813999176 0;1 0.439215689897537 0;1 0.376470595598221 0;1 0.313725501298904 0;1 0.250980406999588 0;1 0.18823529779911 0;1 0.125490203499794 0;1 0.062745101749897 0;1 0 0;0.937254905700684 0 0;0.874509811401367 0 0;0.811764717102051 0 0;0.752941191196442 0 0;0.690196096897125 0 0;0.627451002597809 0 0;0.564705908298492 0 0;0.501960813999176 0 0]);

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',[1 3 5 7 9 11],...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',[1 3 5 7 9 11],...
    'FontSize',16,...
    'CLim',[81.1597 81.8726]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 11]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 11]);
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(zdata1,'Parent',axes1);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% Create xlabel
xlabel('\alpha','FontSize',16);

% Create ylabel
ylabel('\beta','FontSize',16);

% Create zlabel
zlabel('Tweet-level Accuracy','FontSize',16);

% Create colorbar
colorbar('peer',axes1,'FontSize',16);

