disp('Demo for product entity resolution with Basic Graph Summarization');
rng(1234567);
t=cputime;
load product2attr.txt;
G=spconvert(product2attr);
addpath(genpath('../../../'));
G=normalize_X(G);
n=size(G,1);
load product2product.txt;
sim=sparse(product2product(:,1),product2product(:,2),product2product(:,3),n,n);
sim=normalize_X(sim);
A=cell(2,2);
A{1,1}=sim;
A{1,2}=G;
IOtime=cputime-t;
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[20,20]);
name=cell(2,1);
name{1,1}='productcluster-20.txt';
name{2,1}='attrcluster-20.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 20 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[40,40]);
name=cell(2,1);
name{1,1}='productcluster-40.txt';
name{2,1}='attrcluster-40.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 40 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[80,80]);
name=cell(2,1);
name{1,1}='productcluster-80.txt';
name{2,1}='attrcluster-80.txt';
SaveclusterSparse(C, name);
name{1,1}='productclass-80.txt';
name{2,1}='attrclass-80.txt';
Saveclustering(C,name);
e=cputime-t;
disp('super node 80 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[160,160]);
name=cell(2,1);
name{1,1}='productcluster-160.txt';
name{2,1}='attrcluster-160.txt';
SaveclusterSparse(C, name);
name{1,1}='productclass-160.txt';
name{2,1}='attrclass-160.txt';
Saveclustering(C,name);
e=cputime-t;
disp('super node 160 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[320,320]);
name=cell(2,1);
name{1,1}='productcluster-320.txt';
name{2,1}='attrcluster-320.txt';
SaveclusterSparse(C, name);
name{1,1}='productclass-320.txt';
name{2,1}='attrclass-320.txt';
Saveclustering(C,name);
e=cputime-t;
disp('super node 320 running time');
disp(e);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[640,640]);
name=cell(2,1);
name{1,1}='productcluster-640.txt';
name{2,1}='attrcluster-640.txt';
SaveclusterSparse(C, name);
name{1,1}='productclass-640.txt';
name{2,1}='attrclass-640.txt';
Saveclustering(C,name);
e=cputime-t;
disp('super node 640 running time');
disp(e+IOtime);





