disp('Demo for product entity resolution with Advanced Graph Summarization');
rng(1234567);
t=cputime;
load product2attr.txt;
G=spconvert(product2attr);
clear product2attr;
addpath(genpath('../../../'));
G=G./max(max(G));
n=size(G,1);
m=size(G,2);
load product2product.txt;
sim=sparse(product2product(:,1),product2product(:,2),product2product(:,3),n,n);
sim=normalize_X(sim);
clear product2product;
load attr2attr.txt;
sim2=sparse(attr2attr(:,1),attr2attr(:,2),attr2attr(:,3),m,m);
sim2=normalize_X(sim2);
A=cell(2,2);
A{1,1}=sim;
A{1,2}=G;
A{2,2}=sim2;
[~,C,~]=GraphSumPlus(A);
name=cell(2,1);
name{1,1}='productcluster-search.txt';
name{2,1}='attrcluster-search.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp(e);
