rng(1247)
t=cputime;
load author2attr.txt;
load paper2word.txt;
load author2paper.txt;
load paper2paper.txt;
load author2author.txt;
A=cell(4,4);
A{1,2}=spconvert(author2paper);
A{1,3}=spconvert(author2attr);
A{2,4}=spconvert(paper2word);
A{2,4}=A{2,4}./max(max(A{2,4}));
n=size(A{1,2},1);
m=size(A{1,2},2);
sim=sparse(author2author(:,1),author2author(:,2),author2author(:,3),n,n);
sim=sim./max(max(sim));
sim2=sparse(paper2paper(:,1),paper2paper(:,2),paper2paper(:,3),m,m);
sim2=sim2./max(max(sim2));
A{1,1}=sim;
A{2,2}=sim2;
addpath(genpath('../../../'));
IOtime=cputime-t;
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[20,20,20,20]);
name=cell(4,1);
name{1,1}='authorcluster-20.txt';
name{2,1}='papercluster-20.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 20 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[40,40,40,40]);
name=cell(4,1);
name{1,1}='authorcluster-40.txt';
name{2,1}='papercluster-40.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 40 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[80,80,80,80]);
name=cell(4,1);
name{1,1}='authorcluster-80.txt';
name{2,1}='papercluster-80.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 80 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[160,160,160,160]);
name=cell(4,1);
name{1,1}='authorcluster-160.txt';
name{2,1}='papercluster-160.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 160 running time');
disp(e+IOtime);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[320,320,320,320]);
name=cell(4,1);
name{1,1}='authorcluster-320.txt';
name{2,1}='papercluster-320.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 320 running time');
disp(e);
t=cputime;
[~,C,~]=GraphSum(A,'clusters',[640,640,640,640]);
name=cell(4,1);
name{1,1}='authorcluster-640.txt';
name{2,1}='papercluster-640.txt';
SaveclusterSparse(C, name);
e=cputime-t;
disp('super node 640 running time');
disp(e+IOtime);

